### PR TITLE
Frontend env vars 12factorapp compliance

### PR DESCRIPTION
**Pull request by linearcombination**
Proper fix for frontend env vars setting via env vars

This allows the frontend's BACKEND_API_URL to be set via environment
variables at (Docker) image build time per compliance with 12factorapp
principles.

Tested all build cases successfully.

### CODE REVIEW

**Comment by linearcombination** [comment]
Ran into an issue that I need to work out on the use of BACKEND_API_URL. Tested the build cases, but didn't fully retest the UI (until now), so have to hold this back for just a bit while I iron that out.

**Comment by linearcombination** [comment]
I took the opportunity to also squeeze in a couple other minor things: proper media/mime types for epub and docx downloads; and made a visual tweak to the download page to make some buttons closer together.

**Comment by linearcombination** [comment]
Added another commit that only shows epub and docx download options if compact print format is not chosen. Details in commit message.

**Comment by linearcombination** [comment]
Added another commit to fix an issue wherein translation words were being included in generated document more than once per language.

**Comment by linearcombination** [comment]
Added another commit that puts back CORS ORIGIN for production. A previous commit some time ago accidentally removed it.

**Review by danparisd — CHANGES_REQUESTED** [review]
I don't think this actually does what 12 factor requires, at least it doesn't based on my testing.

This looks like it allows for setting the env vars at build time, but 12 factor requires the vars to be able to be set at run time. Based on my research, this is actually kind of tricky with bundled (and compiled) javascript framworks. We want to set the env vars at runtime so that dev and prod can use the same image, but different backends. This keeps dev/prod parity as close as possible, and allows the config to be stored in the environment at runtime.

It's possible I misunderstand the code, or did something wrong in my testing, so let me know if so, or if you need any additional info.

**Comment by linearcombination** [comment]
You are correct. It does only set env vars at build time. I'll work on making it possible to do at runtime.

**Comment by analyticd** [comment]
If you are interested, I have a discussion going here, https://github.com/ElMassimo/vite-plugin-environment/discussions/10, with the author of vite-plugin-environment on this topic. You may be interested in it. Last evening I took a stab at the solution mentioned above, https://developers.redhat.com/blog/2021/03/04/making-environment-variables-accessible-in-front-end-containers#create_a_skeleton_application, and haven't gotten it to work yet, so will do more toward that end. However, in the comments of that article a couple people mentioned that even if you were able to substitute env vars, say to the window javascript object, at runtime, the client's browser will cache them making it difficult (impossible?) to update them. I hadn't thought about that and the author of that article admitted he hadn't either more or less.  Do you have experience with other JS apps getting env vars at runtime? Perhaps we could emulate what those apps do? I'd love to get your input on that.

**Comment by linearcombination** [comment]
Ok, we should be good to go now if you want to test. I've tested locally pretty extensively and I can definitely re-parameterize via env var BACKEND_API_URL at runtime a previously built Docker image.

**Review by danparisd — CHANGES_REQUESTED** [review]
I tested these changes and they work! Good job moving this towards 12factor.

In talking with Craig and Will (our frontend/js guru) I was wondering if instead of inserting the vars into the bundled files if we could insert them into a static js page that's deployed as an asset (no bundling). I'm concerned that there could be changes to the bundler/compiler that are beyond our control that could break the insertion and therefore break bringing up nginx.

Let me know your thoughts on this.

**Comment by linearcombination** [comment]
Thanks for the nudge. The commits I just pushed address those concerns and worked well in testing.

**Comment by danparisd** [comment]
Nice. I like that. it's quite clean and neat. I'll test it tomorrow and get it deployed. Thanks!

**Comment by linearcombination** [comment]
Thank you for all you do!

**Comment by linearcombination** [comment]
Please let me know when you guys have reviewed so that I can merge and you can deploy.

**Comment by danparisd** [comment]
@linearcombination The build is broken. Looks to be changes to pip dependency on https://github.com/linearcombination/USFM-Tools.

Having some experience with python dependencies in Docker builds, my recommendation would be to git tag that repo with a semantic version and point this project's requirements.txt at the appropriate git tag. That way as you continue development you can update the tag as needed.

We may also want to move that usfm-tools repo over to WA so it can be code reviewed as well, but I'll leave that to @PurpleGuitar 's discretion. If we did that we could potentially start pushing that package to pypi and using semver to allow pip to manage the package version, assuming versioning is semver.org compliant. I haven't ever set up pypi publishing, but it seems like something we could do if it were beneficial.

**Comment by danparisd** [comment]
@linearcombination The build is broken. Looks to be changes to pip dependency on https://github.com/linearcombination/USFM-Tools.

Having some experience with python dependencies in Docker builds, my recommendation would be to git tag that repo with a semantic version and point this project's requirements.txt at the appropriate git tag. That way as you continue development you can update the tag as needed.

We may also want to move that usfm-tools repo over to WA so it can be code reviewed as well, but I'll leave that to @PurpleGuitar 's discretion. If we did that we could potentially start pushing that package to pypi and using semver to allow pip to manage the package version, assuming versioning is semver.org compliant. I haven't ever set up pypi publishing, but it seems like something we could do if it were beneficial.

**Comment by linearcombination** [comment]
Thanks for the catch. I’ve got a fix coming tomorrow. I’ll update when it is fully tested. The fix includes your suggestion.

**Comment by linearcombination** [comment]
All unit tests and integration tests passed.

**Comment by danparisd** [comment]
> All unit tests and integration tests passed.

Great thanks! I'll test today.

**Comment by danparisd** [comment]
@linearcombination busted again...dependency conflict between this project and usfm-tools on pyparsing version. Locally I changed this project to pyparsing 3.0.9 and I'm running the tests now.

Error here:
https://github.com/WycliffeAssociates/DOC/actions/runs/3383229521/jobs/5647925535#step:4:1761

**Comment by linearcombination** [comment]
Thanks for the heads up and link. Couldn’t replicate the build failure locally with Docker, but I relaxed the version specs on USFM-Tools so that pip can resolve to whatever it needs for DOC. Seeing successful build locally and on github action now.

**Pull request merged**
